using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public abstract class CollectibleBase : MonoBehaviour
{
    // Start is called before the first frame update
    protected abstract void Collect(Player player);

    [SerializeField] float _movementSpeed = 1;
    protected float MovementSpeed => _movementSpeed;

    [SerializeField] ParticleSystem _collectParticles;
    [SerializeField] AudioClip _collectSound;

    Rigidbody _rb;
    // Update is called once per frame

    private void Awake()
    {
        _rb = GetComponent<Rigidbody>();
    }

    private void FixedUpdate()
    {
        Movement(_rb);
    }

    protected virtual void Movement(Rigidbody rb) 
    {
        Quaternion turnOffset = Quaternion.Euler(0, _movementSpeed, 0);
        rb.MoveRotation(_rb.rotation * turnOffset);
    }

    private void OnTriggerEnter(Collider other)
    {
        Player player = other.gameObject.GetComponent<Player>();
        if (player != null) 
        {
            Collect(player);
            Feedback();

            gameObject.SetActive(false);
        }
    }

    private void Feedback() 
    {
        if (_collectParticles != null) 
        {
            _collectParticles = Instantiate(_collectParticles, transform.position, Quaternion.identity);
        }
        if (_collectSound != null) 
        {
            AudioHelper.PlayClip2D(_collectSound, 1f);
        }
    }
}
